import Phaser from 'phaser';
import { CREATURE, COLORS, WORLD, resolveCreatureTuning, type CreatureTuning, type OrganismPalette } from '../config';
import { Rng } from '../lib/rng';
import { compass } from '../lib/compass';
import { ambientParticles, applyCameraFx } from '../lib/atmosphere';
import { setupWorld } from '../lib/worldCamera';
import { withinRange } from '../lib/geometry';
import { Minimap, type MinimapEntry } from '../ui/Minimap';
import { generateTerrain, inWater, type Terrain, type Nest } from '../systems/terrain';
import { respawnDelay } from '../systems/ecology';
import { featureTexture, nestTexture, HERBIVORES, PREDATORS, KIN_SPECIES } from '../data/sprites/creatureSprites';
import { Creature } from '../entities/Creature';
import { Food } from '../entities/Food';
import { WildCreature } from '../entities/WildCreature';
import { TraitEngine } from '../traits/TraitEngine';
import {
    initialCreatureVitals,
    tickCreatureVitals,
    eatWith,
    damageCreature,
    addNourishment,
    packNourishRate,
    creatureObjectiveProgress,
    isCreatureStageComplete,
    isCreatureStageFailed,
    type CreatureVitals,
} from '../systems/creatureVitals';
import type { EventBus } from '../bootstrap/events';
import type { AppearanceV2 } from '../data/cell-parts';

export interface CreatureSceneData {
    bus: EventBus;
    seed: string;
    species: string;
    resources?: Partial<CreatureVitals>;
    traits?: string[]; // inherited from earlier stages
    palette?: OrganismPalette;
    appearance?: AppearanceV2;
    diet?: 'herbivore' | 'carnivore';
}

/** A nest plus its live scene state: finite food and minimap discovery. */
interface NestState {
    nest: Nest;
    discovered: boolean;
    foods: Food[];
}

/**
 * Stage 2 — Creature. A big top-down scrolling world (WORLD.creatureWidth×
 * creatureHeight) generated by systems/terrain: biomes, woods, impassable
 * ponds and ~9 food nests spread map-wide. Forage nest to nest to keep hunger
 * down, dodge predator territories, meet kin to form a pack and gather enough
 * nourishment to raise young. Rules live in systems/creatureVitals; wild
 * behavior in entities/WildCreature. The scene owns rendering, input and the
 * world, and talks to the DOM HUD only through the EventBus.
 */
export class CreatureScene extends Phaser.Scene {
    private bus!: EventBus;
    private seed = 'default';
    private species = 'Your lineage';
    private initialResources?: Partial<CreatureVitals>;
    private inherited: string[] = [];
    private palette?: OrganismPalette;
    private appearance?: AppearanceV2;
    private diet: 'herbivore' | 'carnivore' | null = null;
    private awaitingDiet = false;

    private rng!: Rng;
    private terrain!: Terrain;
    private creature!: Creature;
    private nests: NestState[] = [];
    private wilds: WildCreature[] = [];
    private kin: WildCreature[] = [];
    /** Starting head-count per herbivore species — the ceiling that population
     * homeostasis recovers toward (Tier 3). */
    private herbBaseline = new Map<string, number>();
    private minimap!: Minimap;
    private packSize = 0;
    private lastHitAt = -9999;
    private currentThreat: string | null = null;
    private bounds!: Phaser.Geom.Rectangle;
    private vitals: CreatureVitals = initialCreatureVitals();

    private traitEngine = new TraitEngine();
    private owned = new Set<string>();
    private tuning: CreatureTuning = resolveCreatureTuning();

    private keys!: Record<'up' | 'down' | 'left' | 'right', Phaser.Input.Keyboard.Key>;
    private cursors!: Phaser.Types.Input.Keyboard.CursorKeys;
    private pointerActive = false;
    private speedMultiplier = 1;
    private paused = false;
    private ended = false;
    private hudAccumulator = 0;
    private minimapAccumulator = 0;

    constructor() {
        super('Creature');
    }

    init(data: CreatureSceneData): void {
        this.bus = data.bus;
        this.seed = data.seed ?? this.seed;
        this.species = data.species ?? this.species;
        this.initialResources = data.resources;
        this.inherited = data.traits ?? [];
        this.palette = data.palette;
        this.appearance = data.appearance;
        this.diet = data.diet ?? null;
    }

    create(): void {
        this.rng = new Rng(`${this.seed}:creature`);
        this.vitals = { ...initialCreatureVitals(), ...this.initialResources };
        this.owned = new Set(this.inherited);
        this.tuning = resolveCreatureTuning(this.traitEngine.aggregateEffects(this.owned));
        this.ended = false;
        this.minimapAccumulator = 0;

        const W = WORLD.creatureWidth;
        const H = WORLD.creatureHeight;
        this.terrain = generateTerrain(this.seed, W, H);

        this.cameras.main.setBackgroundColor(COLORS.bg);
        this.renderTerrain(W, H);

        ambientParticles(this, { width: W, height: H, color: COLORS.secondary, rise: false, depth: 26, frequency: 120, scale: [0.05, 0.16], alpha: 0.3 });
        applyCameraFx(this.cameras.main, 0.7, 0.45);

        const margin = 60;
        this.bounds = new Phaser.Geom.Rectangle(margin, margin, W - margin * 2, H - margin * 2);

        this.creature = new Creature(this, W / 2, H / 2, this.palette, this.appearance);
        this.creature.applyVisuals(this.traitEngine.aggregateVisuals(this.owned));

        this.spawnNests();
        this.spawnWildlife(W, H);
        this.packSize = 0;
        this.currentThreat = null;
        this.lastHitAt = -9999;

        setupWorld(this, { width: W, height: H }, { follow: this.creature.container, zoom: 1, lerp: 0.08 });
        this.minimap = new Minimap(this, { width: W, height: H });
        this.updateMinimap(); // paint once immediately; update() throttles it thereafter

        const kb = this.input.keyboard!;
        this.keys = {
            up: kb.addKey(Phaser.Input.Keyboard.KeyCodes.W),
            down: kb.addKey(Phaser.Input.Keyboard.KeyCodes.S),
            left: kb.addKey(Phaser.Input.Keyboard.KeyCodes.A),
            right: kb.addKey(Phaser.Input.Keyboard.KeyCodes.D),
        };
        this.cursors = kb.createCursorKeys();
        this.input.on('pointerdown', () => (this.pointerActive = true));
        this.input.on('pointerup', () => (this.pointerActive = false));

        this.bus.on('intent:pause', () => {
            this.paused = true;
            this.emitSnapshot();
        });
        this.bus.on('intent:resume', () => (this.paused = false));
        this.bus.on('intent:set-speed', ({ multiplier }) => (this.speedMultiplier = multiplier));
        this.bus.on('intent:acquire-trait', ({ traitId }) => this.acquireTrait(traitId));
        this.bus.on('intent:retry', () => this.retry());

        // Dev toolbar accelerators (buttons only exist in the local env).
        this.bus.on('intent:dev-grant', () => {
            this.vitals = { ...this.vitals, hunger: 0, health: 100 };
            this.emitHud();
        });
        this.bus.on('intent:dev-complete', () => {
            this.vitals = { ...this.vitals, nourishment: CREATURE.objectiveTarget };
            this.emitHud();
        });
        this.bus.on('intent:dev-die', () => {
            if (!this.ended) this.failStage();
        });

        this.time.addEvent({ delay: 15000, loop: true, callback: () => this.emitSnapshot() });

        // Diet: pick herbivore vs carnivore at the start of the stage (or
        // restore a saved choice). The sim waits on the choice.
        this.bus.on('intent:choose-diet', ({ diet }) => this.chooseDiet(diet));
        if (this.diet) {
            this.showCreatureOnboarding();
        } else {
            this.awaitingDiet = true;
            this.bus.emit('creature:choose-diet', undefined);
        }

        this.emitHud();
        this.emitTraits();
        this.emitSnapshot();
    }

    private chooseDiet(diet: 'herbivore' | 'carnivore'): void {
        if (this.diet) return;
        this.diet = diet;
        this.awaitingDiet = false;
        this.emitSnapshot();
        this.showCreatureOnboarding();
    }

    /** First-time coach marks that explain how Stage 2 plays (diet-aware). */
    private showCreatureOnboarding(): void {
        const hunt = this.diet === 'carnivore';
        this.bus.emit('onboarding:show', {
            stageId: `creature-${this.diet}`,
            steps: [
                { id: 'move', title: 'A wider world', text: 'Steer with WASD or the arrow keys, or hold the pointer to swim toward it. Roam the land to survive and raise your young.' },
                { id: 'feed', title: hunt ? 'Hunt to feed' : 'Forage to feed', text: hunt
                    ? 'As a carnivore, chase and catch the grazing creatures for rich meals — plants barely sustain you. Fullness (top-left) drops as you go; let it empty and your health drains.'
                    : 'As a herbivore, graze the food at nests scattered across the map. Fullness (top-left) drops as you go; let it empty and your health drains.' },
                { id: 'grow', title: 'Evolve as you feed', text: 'Every meal banks evolution — open Traits (bottom-right) to buy adaptations like faster legs or stronger jaws.' },
                { id: 'kin', title: 'Kin & predators', text: 'Meet others of your kind to form a pack that helps raise your young. Beware territorial predators guarding their dens.' },
            ],
        });
    }

    /** Draw the generated habitat: ground, biome tints, ponds and features. */
    private renderTerrain(W: number, H: number): void {
        const ground = this.add.graphics().setDepth(-4);
        ground.fillGradientStyle(0x13291b, 0x112616, 0x0a1a12, 0x0b1c15, 1);
        ground.fillRect(0, 0, W, H);

        const tints = this.add.graphics().setDepth(-3);
        const biomeTint: Record<string, [number, number]> = {
            meadow: [0x3f7d43, 0.08],
            forest: [0x1f4d33, 0.18],
            rock: [0x5a6068, 0.1],
        };
        for (const b of this.terrain.biomes) {
            const [color, alpha] = biomeTint[b.kind];
            tints.fillStyle(color, alpha);
            tints.fillEllipse(b.x, b.y, b.rx * 2, b.ry * 2);
        }

        const water = this.add.graphics().setDepth(-2);
        for (const w of this.terrain.waters) {
            water.fillStyle(0x0a2e38, 0.9);
            water.fillEllipse(w.x, w.y, (w.rx + 14) * 2, (w.ry + 14) * 2); // soft bank
            water.fillStyle(0x143c42, 1);
            water.fillEllipse(w.x, w.y, w.rx * 2, w.ry * 2);
            water.fillStyle(0x2b9c8b, 0.16);
            water.fillEllipse(w.x - w.rx * 0.2, w.y - w.ry * 0.25, w.rx * 1.1, w.ry * 0.8);
            water.lineStyle(2, COLORS.brandDeep, 0.5);
            water.strokeEllipse(w.x, w.y, w.rx * 2, w.ry * 2);
        }

        // Features: cached textures; trees canopy above the creatures.
        const deco = new Rng(`${this.seed}:deco`);
        for (const f of this.terrain.features) {
            const img = this.add.image(f.x, f.y, featureTexture(this, f.kind, f.variant));
            img.setScale(f.scale);
            img.setDepth(f.kind === 'tree' ? 22 : f.kind === 'bush' || f.kind === 'rock' ? 2 : 1);
            if (f.kind === 'grass' || f.kind === 'flower' || f.kind === 'tree') {
                img.setRotation((deco.next() - 0.5) * (f.kind === 'tree' ? Math.PI * 2 : 0.6));
            }
        }
    }

    /** Nests: a sprite plus a finite clutch of food scattered around each. */
    private spawnNests(): void {
        this.nests = this.terrain.nests.map((nest) => {
            this.add.image(nest.x, nest.y, nestTexture(this)).setDepth(3);
            const foods: Food[] = [];
            for (let i = 0; i < CREATURE.foodPerNest; i++) {
                const a = (i / CREATURE.foodPerNest) * Math.PI * 2 + this.rng.next() * 1.2;
                const d = 46 + this.rng.next() * 60;
                foods.push(new Food(this, nest.x + Math.cos(a) * d, nest.y + Math.sin(a) * d));
            }
            return { nest, discovered: false, foods };
        });
    }

    /** Herbivore herds at nests, predators in territories, kin roaming. */
    private spawnWildlife(W: number, H: number): void {
        this.wilds = [];
        this.kin = [];

        // Each nest hosts a herd of one herbivore species (round-robin).
        this.terrain.nests.forEach((nest, i) => {
            const def = HERBIVORES[i % HERBIVORES.length];
            for (let n = 0; n < def.groupSize; n++) {
                this.wilds.push(new WildCreature(this, this.rng, this.bounds, def, nest, this.terrain.waters, this.wilds.length));
            }
        });

        // Predator dens, kept away from the spawn and nests. With a wider
        // predator roster we place fewer dens each so territories don't crowd;
        // each den can host a small pack (def.groupSize) for pack-hunters.
        const dens: Array<{ x: number; y: number }> = [];
        const densPerSpecies = PREDATORS.length >= 4 ? 1 : 2;
        for (const def of PREDATORS) {
            for (let n = 0; n < densPerSpecies; n++) {
                let den = { x: W * 0.25, y: H * 0.25 };
                for (let tries = 0; tries < 40; tries++) {
                    const x = 300 + this.rng.next() * (W - 600);
                    const y = 300 + this.rng.next() * (H - 600);
                    const clear = Math.hypot(x - W / 2, y - H / 2) > 1100
                        && !inWater(this.terrain.waters, x, y, 200)
                        && this.terrain.nests.every((nst) => Math.hypot(x - nst.x, y - nst.y) > 620)
                        && dens.every((d) => Math.hypot(x - d.x, y - d.y) > 900);
                    if (clear) {
                        den = { x, y };
                        break;
                    }
                }
                dens.push(den);
                // A faint blood-tinted ring marks the territory on the ground.
                const ring = this.add.graphics().setDepth(0);
                ring.fillStyle(COLORS.danger, 0.03);
                ring.fillCircle(den.x, den.y, def.territoryRadius);
                ring.lineStyle(2, COLORS.danger, 0.12);
                ring.strokeCircle(den.x, den.y, def.territoryRadius);
                // A den hosts a small pack; solitary hunters use groupSize 1.
                for (let m = 0; m < def.groupSize; m++) {
                    this.wilds.push(new WildCreature(this, this.rng, this.bounds, def, den, this.terrain.waters, this.wilds.length));
                }
            }
        }

        // Kin scattered across the land, waiting to be met.
        for (let i = 0; i < CREATURE.kinCount; i++) {
            let home = { x: W / 2 + 400, y: H / 2 };
            for (let tries = 0; tries < 30; tries++) {
                const x = this.bounds.left + this.rng.next() * this.bounds.width;
                const y = this.bounds.top + this.rng.next() * this.bounds.height;
                if (!inWater(this.terrain.waters, x, y, 60)) {
                    home = { x, y };
                    break;
                }
            }
            this.kin.push(new WildCreature(this, this.rng, this.bounds, KIN_SPECIES, home, this.terrain.waters, i));
        }

        // Record the starting herbivore population per species: the ceiling that
        // population homeostasis recovers toward after predation thins a herd.
        this.herbBaseline.clear();
        for (const w of this.wilds) {
            if (w.def.role === 'herbivore') this.herbBaseline.set(w.speciesId, (this.herbBaseline.get(w.speciesId) ?? 0) + 1);
        }
    }

    /** Homeostatic respawn delay for an eaten herbivore: a thinned species comes
     * back quickly, a full one slowly — bounded swings, never extinction. */
    private herbRespawnDelay(herb: WildCreature, aliveCounts: Map<string, number>): number {
        const baseline = this.herbBaseline.get(herb.speciesId) ?? 1;
        const alive = aliveCounts.get(herb.speciesId) ?? 1;
        return respawnDelay(alive, baseline, 4, 14);
    }

    private readInput(): { vx: number; vy: number } {
        let dx = 0;
        let dy = 0;
        if (this.keys.left.isDown || this.cursors.left.isDown) dx -= 1;
        if (this.keys.right.isDown || this.cursors.right.isDown) dx += 1;
        if (this.keys.up.isDown || this.cursors.up.isDown) dy -= 1;
        if (this.keys.down.isDown || this.cursors.down.isDown) dy += 1;

        if (this.pointerActive && dx === 0 && dy === 0) {
            const p = this.input.activePointer.positionToCamera(this.cameras.main) as Phaser.Math.Vector2;
            const ang = Phaser.Math.Angle.Between(this.creature.x, this.creature.y, p.x, p.y);
            if (Phaser.Math.Distance.Between(this.creature.x, this.creature.y, p.x, p.y) > 6) {
                dx = Math.cos(ang);
                dy = Math.sin(ang);
            }
        }

        const len = Math.hypot(dx, dy);
        if (len > 0) {
            dx /= len;
            dy /= len;
        }
        return { vx: dx * this.tuning.speed, vy: dy * this.tuning.speed };
    }

    update(_time: number, delta: number): void {
        if (this.paused || this.ended || this.awaitingDiet) return;
        const dt = (delta / 1000) * this.speedMultiplier;

        const { vx, vy } = this.readInput();
        this.creature.setVelocity(vx, vy);
        this.creature.update(dt, this.bounds, (x, y) => inWater(this.terrain.waters, x, y, -this.creature.radius * 0.4));

        // Nests: discovery for the minimap, finite food with timed respawns.
        for (const state of this.nests) {
            if (!state.discovered && withinRange(this.creature.x, this.creature.y, state.nest.x, state.nest.y, CREATURE.nestDiscoverRadius)) {
                state.discovered = true;
            }
            for (const item of state.foods) {
                item.update(dt);
                if (item.consumed) continue;
                const reach = this.creature.radius + CREATURE.foodRadius + CREATURE.bitePadding;
                if (withinRange(this.creature.x, this.creature.y, item.x, item.y, reach)) {
                    item.eat();
                    // Carnivores get little from plants; herbivores thrive on them.
                    this.vitals = eatWith(this.vitals, this.tuning, this.diet === 'carnivore' ? 0.4 : 1);
                    this.bus.emit('sfx', { name: 'absorb' });
                }
            }
        }

        // Wild species: herbivores flee, predators defend their territory.
        // One player-position object for the frame, shared by the wild and kin
        // loops below — avoids a throwaway literal per entity every frame.
        const player = { x: this.creature.x, y: this.creature.y };
        // Tier 2 perception: split alive wildlife once per frame so each creature
        // can see its herd (cohesion/scatter) and hunt/flee the right others.
        const aliveHerbivores: WildCreature[] = [];
        const alivePredators: WildCreature[] = [];
        const herbAlive = new Map<string, number>();
        for (const w of this.wilds) {
            if (w.consumed) continue;
            if (w.def.role === 'herbivore') {
                aliveHerbivores.push(w);
                herbAlive.set(w.speciesId, (herbAlive.get(w.speciesId) ?? 0) + 1);
            } else if (w.def.role === 'predator') {
                alivePredators.push(w);
            }
        }
        const wildCtx = { herbivores: aliveHerbivores, predators: alivePredators };
        let nearestDist = Infinity;
        let nearestHunter: WildCreature | null = null;
        for (const wild of this.wilds) {
            const dist = wild.update(dt, player, wildCtx);
            if (wild.chasing && dist < nearestDist) {
                nearestDist = dist;
                nearestHunter = wild;
            }
            // Carnivores hunt the grazing creatures for a rich meal.
            if (this.diet === 'carnivore' && wild.def.role === 'herbivore' && !wild.consumed) {
                if (dist <= this.creature.radius + wild.radius) {
                    wild.eaten(this.herbRespawnDelay(wild, herbAlive));
                    this.vitals = eatWith(this.vitals, this.tuning, 5);
                    this.bus.emit('sfx', { name: 'absorb-rich' });
                    this.cameras.main.shake(70, 0.003);
                }
                continue;
            }
            if (wild.def.role !== 'predator') continue;

            // Tier 3: a hungry predator that reaches a grazer makes a kill. The
            // herd thins here and recovers elsewhere via population homeostasis;
            // the predator is sated and calms down. No camera shake — these hunts
            // usually happen away from the player.
            if (wild.isHunting) {
                for (const herb of aliveHerbivores) {
                    if (herb.consumed) continue;
                    if (Phaser.Math.Distance.Between(wild.x, wild.y, herb.x, herb.y) <= wild.radius + herb.radius) {
                        herb.eaten(this.herbRespawnDelay(herb, herbAlive));
                        wild.feed();
                        this.bus.emit('sfx', { name: 'absorb' });
                        break;
                    }
                }
            }

            const contact = this.creature.radius + wild.radius;
            if (dist <= contact && _time - this.lastHitAt >= CREATURE.predatorHitCooldownMs) {
                this.lastHitAt = _time;
                this.vitals = damageCreature(this.vitals, wild.def.damage);
                this.knockback(wild);
                this.cameras.main.shake(120, 0.006);
                this.bus.emit('sfx', { name: 'hit' });
            }
        }
        this.currentThreat = nearestHunter && nearestDist <= CREATURE.predatorAlertRadius
            ? `${nearestHunter.def.name} — flee ${compass(this.creature.x - nearestHunter.x, this.creature.y - nearestHunter.y)}`
            : null;

        // Kin: meet members of your species; a pack passively helps raise young.
        let pack = 0;
        this.kin.forEach((k, i) => {
            k.update(dt, player, { slotAngle: (i / CREATURE.kinCount) * Math.PI * 2 });
            if (k.joined) {
                pack++;
            } else if (withinRange(this.creature.x, this.creature.y, k.x, k.y, this.creature.radius + CREATURE.kinRadius + CREATURE.kinJoinPadding)) {
                k.join();
                pack++;
                this.bus.emit('sfx', { name: 'kin' });
            }
        });
        this.packSize = pack;
        if (pack > 0) this.vitals = addNourishment(this.vitals, packNourishRate(pack) * dt);

        this.vitals = tickCreatureVitals(this.vitals, dt, this.tuning);

        // Decorative minimap: redraw ~every 100ms rather than every frame (see
        // CellScene) — a few-frame lag on the dots is invisible.
        this.minimapAccumulator += delta;
        if (this.minimapAccumulator >= 100) {
            this.minimapAccumulator = 0;
            this.updateMinimap();
        }

        this.hudAccumulator += delta;
        if (this.hudAccumulator >= 100) {
            this.hudAccumulator = 0;
            this.emitHud();
            this.emitTraits();
        }

        if (isCreatureStageComplete(this.vitals)) return this.completeStage();
        if (isCreatureStageFailed(this.vitals)) return this.failStage();
    }

    private updateMinimap(): void {
        const entries: MinimapEntry[] = [
            { x: this.creature.x, y: this.creature.y, color: COLORS.brandHi, size: 3.5 },
        ];
        for (const state of this.nests) {
            if (state.discovered) entries.push({ x: state.nest.x, y: state.nest.y, color: COLORS.food, size: 2.5 });
        }
        for (const k of this.kin) {
            entries.push({ x: k.x, y: k.y, color: COLORS.evolution, size: 2, alpha: k.joined ? 1 : 0.7 });
        }
        // Predator territory warnings appear only within sense range.
        for (const wild of this.wilds) {
            if (wild.def.role !== 'predator') continue;
            if (!withinRange(this.creature.x, this.creature.y, wild.x, wild.y, CREATURE.senseRadius)) continue;
            entries.push({ x: wild.x, y: wild.y, color: COLORS.danger, size: 2.5 });
        }
        this.minimap.update(entries);
    }

    private knockback(predator: WildCreature): void {
        const ang = Phaser.Math.Angle.Between(predator.x, predator.y, this.creature.x, this.creature.y);
        const nx = Phaser.Math.Clamp(this.creature.x + Math.cos(ang) * CREATURE.predatorKnockback, this.bounds.left + this.creature.radius, this.bounds.right - this.creature.radius);
        const ny = Phaser.Math.Clamp(this.creature.y + Math.sin(ang) * CREATURE.predatorKnockback, this.bounds.top + this.creature.radius, this.bounds.bottom - this.creature.radius);
        if (!inWater(this.terrain.waters, nx, ny)) this.creature.container.setPosition(nx, ny);
    }

    private emitHud(): void {
        this.bus.emit('hud:update', {
            species: this.species,
            stage: 'Stage 2 · Creature',
            energy: Math.round(100 - this.vitals.hunger), // Fullness
            integrity: Math.round(this.vitals.health),
            evolution: Math.round(this.vitals.nourishment * 10) / 10,
            energyLabel: 'Fullness',
            integrityLabel: 'Health',
            evolutionLabel: 'Growth',
            objectiveLabel: `Forage to raise young (${Math.floor(this.vitals.nourishment)}/${CREATURE.objectiveTarget})` + (this.packSize > 0 ? ` · pack ${this.packSize}` : ''),
            objectiveProgress: creatureObjectiveProgress(this.vitals),
            threat: this.currentThreat ?? (this.vitals.hunger > 80 ? 'Starving — find a nest' : null),
        });
    }

    private emitTraits(): void {
        // Buyable creature adaptations (spend evolution banked from feeding)…
        const creatureEntries = this.traitEngine.forStage('creature').map((t) => ({
            id: t.id,
            name: t.name,
            description: t.description,
            category: t.category,
            cost: t.cost,
            state: this.traitEngine.resolveState(t, this.owned),
            benefits: t.benefits,
            costs: t.costs,
            affordable: this.traitEngine.canAcquire(t, this.owned, this.vitals.evolution),
            rarity: t.rarity,
            leadsTo: this.traitEngine.leadsTo(t.id),
        }));
        // …plus the Cell-stage traits carried in, shown as permanent.
        const creatureIds = new Set(creatureEntries.map((e) => e.id));
        const inheritedEntries = [...this.owned]
            .filter((id) => !creatureIds.has(id))
            .map((id) => this.traitEngine.get(id))
            .filter((t): t is NonNullable<typeof t> => Boolean(t))
            .map((t) => ({
                id: t.id,
                name: t.name,
                description: t.description,
                category: t.category,
                cost: t.cost,
                state: 'inherited',
                benefits: t.benefits,
                costs: t.costs,
                affordable: false,
                rarity: t.rarity,
                leadsTo: this.traitEngine.leadsTo(t.id),
            }));
        this.bus.emit('traits:update', { entries: [...creatureEntries, ...inheritedEntries], evolution: this.vitals.evolution });
    }

    private recomputeTuning(): void {
        this.tuning = resolveCreatureTuning(this.traitEngine.aggregateEffects(this.owned));
    }

    private refreshVisuals(): void {
        this.creature.applyVisuals(this.traitEngine.aggregateVisuals(this.owned));
    }

    private acquireTrait(traitId: string): void {
        const trait = this.traitEngine.get(traitId);
        if (!trait) return;
        if (!this.traitEngine.canAcquire(trait, this.owned, this.vitals.evolution)) return;

        this.vitals = { ...this.vitals, evolution: this.vitals.evolution - trait.cost };
        this.owned.add(traitId);
        this.recomputeTuning();
        this.refreshVisuals();
        this.bus.emit('sfx', { name: 'evolve' });
        this.emitHud();
        this.emitTraits();
        this.emitSnapshot();
    }

    private emitSnapshot(): void {
        if (this.ended && !isCreatureStageComplete(this.vitals)) return;
        this.bus.emit('save:snapshot', {
            stage: 'creature',
            completed: isCreatureStageComplete(this.vitals),
            traits: [...this.owned],
            resources: {
                hunger: Math.round(this.vitals.hunger),
                health: Math.round(this.vitals.health),
                nourishment: this.vitals.nourishment,
                evolution: this.vitals.evolution,
                ...(this.diet ? { diet: this.diet === 'carnivore' ? 1 : 0 } : {}),
            },
        });
    }

    private completeStage(): void {
        this.ended = true;
        this.emitHud();
        this.emitSnapshot();
        this.bus.emit('sfx', { name: 'complete' });
        this.bus.emit('stage:complete', {
            stage: 'creature',
            nextStage: 'tribe',
            summary: `${this.species} raised its young and established a stable species, carrying ${this.owned.size} inherited adaptations forward.`,
        });
    }

    private failStage(): void {
        // A death moment, then a retry card (mirrors the Cell stage).
        this.ended = true;
        this.currentThreat = null;
        this.bus.emit('sfx', { name: 'hit' });
        this.cameras.main.shake(260, 0.008);
        this.cameras.main.flash(320, 70, 12, 12);
        this.tweens.add({ targets: this.creature.container, alpha: 0, scale: 0.4, angle: 30, duration: 650, ease: 'Cubic.easeIn' });
        this.emitSnapshot();
        this.time.delayedCall(700, () => {
            this.bus.emit('stage:failed', {
                stage: 'creature',
                title: 'The lineage falters',
                summary: `${this.species} fell before raising its young. Try again.`,
            });
        });
    }

    private retry(): void {
        if (!this.ended) return;
        this.scene.restart({
            bus: this.bus,
            seed: this.seed,
            species: this.species,
            traits: this.inherited,
            palette: this.palette,
            appearance: this.appearance,
        } as CreatureSceneData);
    }
}
